---
# Wazuh post-install tasks

- name: Read lme-environment.env file
  ansible.builtin.slurp:
    src: /opt/lme/lme-environment.env
  register: lme_env_content
  become: yes

- name: Set environment variables
  ansible.builtin.set_fact:
    env_dict: "{{ env_dict | default({}) | combine({ item.split('=', 1)[0]: item.split('=', 1)[1] }) }}"
  loop: "{{ (lme_env_content['content'] | b64decode).split('\n') }}"
  when: item != '' and not item.startswith('#')

- name: Set playbook variables
  ansible.builtin.set_fact:
    wazuh_password: "{{ global_secrets.wazuh | default('') }}"
    wazuh_api_password: "{{ global_secrets.wazuh_api | default('') }}"

# Fix Wazuh RBAC
- name: Fix Wazuh RBAC
  ansible.builtin.expect:
    command: "{{ clone_directory }}/scripts/wazuh_rbac.sh"
    responses:
      ".*'wazuh'.*":
        - "{{ wazuh_password }}"
      ".*'wazuh-wui'.*":
        - "{{ wazuh_api_password }}"
    timeout: 240 
  become: yes
  no_log: "{{ not debug_mode }}" 