---
# Common variables for all roles
clone_directory: "{{ clone_dir | default('~/LME') }}"
storage_runroot: "/run/containers/storage"
storage_graphroot: "/var/lib/containers/storage"

# Directory configuration
config_dir: "/etc/lme"
user_config_dir: "/root/.config/containers"
user_vault_dir: "/etc/lme/vault"
user_secrets_conf: "/root/.config/containers/containers.conf"
user_storage_conf: "/root/.config/containers/storage.conf"
global_storage_conf: "/etc/containers/storage.conf"
password_file: "/etc/lme/pass.sh"

# Password configuration
min_length: 12

# Elasticsearch configuration
es_port: 9200
kibana_port: 5601
fleet_port: 8220

# Default timezone settings
timezone_area: "Etc"  # Change to your area: America, Europe, Asia, etc.
timezone_zone: "UTC"  # Change to your timezone: New_York, London, Tokyo, etc. 