---
# Default variables that can be overridden
clone_directory: "~/LME"
storage_runroot: "/run/containers/storage"
storage_graphroot: "/var/lib/containers/storage"

# Directory configuration
config_dir: "/etc/lme"
user_config_dir: "/root/.config/containers"
user_vault_dir: "/etc/lme/vault"
user_secrets_conf: "/root/.config/containers/containers.conf"
user_storage_conf: "/root/.config/containers/storage.conf"
global_storage_conf: "/etc/containers/storage.conf"
password_file: "/etc/lme/pass.sh"

# Password configuration
min_length: 12

# User configuration
install_user: "root"

# Default packages that apply to all distributions if not overridden
common_packages:
  - curl
  - wget
  - gnupg2
  - jq
  - uidmap
  - python3-pexpect

# Ubuntu-specific packages
ubuntu_packages:
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common
  - fuse-overlayfs
  - python3-pip
  - python3-venv
  - build-essential
  - git 