---
# Default variables that can be overridden
# Note: Most common variables are now defined in site.yml

# Default packages that apply to all distributions if not overridden
common_packages:
  - curl
  - wget
  - gnupg2
  - jq
  - uidmap

# Ubuntu-specific packages
ubuntu_packages:
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common
  - fuse-overlayfs
  - build-essential
  - git
  - python3-pip  # Generic pip package
  - python3-pexpect  # Generic pexpect package

# Ubuntu 24.04 specific packages
ubuntu_24_04_packages:
  - python3.12
  - python3.12-venv
  - python3.12-dev

# Ubuntu 22.04 specific packages
ubuntu_22_04_packages:
  - python3.10
  - python3.10-venv
  - python3.10-dev