---
- name: Setup LME
  hosts: localhost
  connection: local
  become: no  # Default to no privilege escalation
  vars:
    clone_directory: "{{ clone_dir | default('~/LME') }}"
    install_user: "{{ ansible_user_id }}"
  roles:
    - base
    - nix
    - podman
    - dashboards
    - wazuh
    - elasticsearch
    - fleet
    
    # - role: wazuh
    #   tags: ['system', 'all']
    