---
- name: Setup LME
  hosts: localhost
  connection: local
  become: no  # Default to no privilege escalation
  vars:
    clone_directory: "{{ clone_dir | default('~/LME') }}"
    install_user: "{{ ansible_user_id }}"
  roles:
    - role: base
      tags: ['base', 'all']
    - role: nix
      tags: ['base', 'all']
    - role: podman
      tags: ['system', 'all']
    - role: elasticsearch
      tags: ['system', 'all']
    - role: dashboards
      tags: ['system', 'all']
    - role: wazuh
      tags: ['system', 'all']
    - role: fleet
      tags: ['system', 'all']
    
    # - role: wazuh
    #   tags: ['system', 'all']
    