---
# Ubuntu-specific variables
ubuntu_packages:
  - jq
  - uidmap
  - nix-bin
  - nix-setup-systemd
  - python3-pexpect
  - fuse-overlayfs

common_packages:
  - curl
  - wget
  - gnupg2

# Directory configuration
config_dir: "/etc/lme"
user_config_dir: "/root/.config/containers"
user_vault_dir: "/etc/lme/vault"
user_secrets_conf: "/root/.config/containers/containers.conf"
user_storage_conf: "/root/.config/containers/storage.conf"
global_storage_conf: "/etc/containers/storage.conf"
password_file: "/etc/lme/pass.sh"

# Password configuration
min_length: 12

# User configuration
install_user: "root" 