---
# Debian-specific Nix setup

- name: Ensure Nix multi-user installation
  shell: |
    if ! command -v nix-env &>/dev/null; then
      curl -L https://nixos.org/nix/install | sh -s -- --daemon
    fi
  args:
    executable: /bin/bash
    creates: /nix/var/nix/profiles/default/bin/nix-env
  become: yes

- name: Add user to nix-users group (create if it doesn't exist)
  user:
    name: "{{ install_user }}"
    groups: "{{ 'nix-users' if 'nix-users' in ansible_facts.getent_group else 'nixbld' }}"
    append: yes
  become: yes

- name: Add Nix channel
  command: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  become: yes

- name: Update Nix channel
  command: nix-channel --update
  become: yes 